### ISSUE TITLE
pymongo.errors.OperationFailure

### ISSUE THREAD

**Issue by sunaifei** [DigitalSlideArchive/HistomicsUI#118]
When I install girder follow the HismoicsUI respository，execute “girder serve”,
I get pymongo.errors as follows:
pymongo.errors.OperationFailure: command createIndexes requires authentication, full error: {'ok': 0.0, 'errmsg': 'command createIndexes requires authentication', 'code': 13, 'codeName': 'Unauthorized'}

**Comment by manthey** [comment]
Did you install Mongo so that it requires authentication?  If so, you'll need to modify the database uri for Girder to include the appropriate credentials.  This is either done in the grider config file or as part of the --database option for "girder serve" -- I'd have to check Mongo documentation to determine how the authentication is included in that uri.

**Comment by manthey** [comment]
Closing without further information.  Feel free to reopen if you have more details.
