### ISSUE TITLE
Need group owner(s) to be able to delete annotation groups

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsUI#19]
Currently, the "x" icon only appears if you are the owner of an annotation, but not if you are the owner of the group. This is necessary to support annotation review capabilities.

**Comment by manthey** [comment]
I think with the new "Create Annotations" access flag, it is finally possible to manage this appropriately.  Users who may create annotations should be in a folder where that flag is set but they only have read access otherwise.  The collection owner has write access and therefore can edit and modify the annotations.

The remaining question is if User A has only "create annotation" access and creates an annotation which is private or read-only to others, should a user with WRITE but not ADMIN permission on the folder be able to modify and delete this annotation?  If so, this would relax the current permissions (but since we now have the "create annotations" flag, there is an appropriate level of access for each case.

**Comment by manthey** [comment]
I'm closing this as I think it has appropriate support.  If not, we need to better define the matrix of permissions and abilities.
