### ISSUE TITLE
Automatically zoom to where annotation is in interactive mode

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/HistomicsUI#33]
Now that the right-click mode has been added, interactive mode is no longer required.

**Comment by manthey** [comment]
I think this shouldn't be automatic, but should be a control.

I would imagine a "jump to" control just to the left of the close control on each annotation.  When clicked, that annotation would be centered, and the zoom would be adjusted so that the annotation was about 1/4 of the display.  We probably wouldn't change the zoom for point annotations.  For other annotations, we probably shouldn't change the zoom if the annotation would fit on the display and is more than some minimum size.

**Comment by manthey** [comment]
@eagw Would you like to try implementing what I just commented?  If you look at the label display, you'll see where we calculate the perimeter of annotations -- that information can be used to glean the bounding box of non-point annotations.  If we don't have an appropriate icon for the control, we can find an svg of such an icon and add it.
